on: 
  push:
  pull_request_review:
  check_run:
    types: [completed]

permissions:
  contents: read
  pull-requests: write
  
jobs:
  build:
    name: Gitflow
    runs-on: ubuntu-16.04
    steps:
    - uses: Logerfo/gitflow-action@0.0.5
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }} # The `GITHUB_TOKEN` secret.
        release: release # The `release` branch.
        release-regex: ^release/(.*) # The regex for `release` branch.
        dev: develop
        master: main
        label: gitflow 
        auto-merge: true
        require-merge: true