on:
  pull_request:
    types:
      - opened
      - closed
      - labeled

permissions:
  contents: read
  pull-requests: write

jobs:
  release_workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: hoangvvo/gitflow-workflow-action@0.1.0
        with:
          develop_branch: "develop"
          main_branch: "main"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}